### ISSUE TITLE
Adding “Slaves”

### ISSUE THREAD

**Issue by JohnNielse** [Vedzaa/NitroSniperGo#1]
Use Alt tokens to snipe on more servers. 

Example, github.com/hellbound1337/nitro-sniper-alt

**Comment by Vedzaa** [comment]
I'm sorry I didn't see your issue until now, I'll add it as soon as possible!

**Comment by Vedzaa** [comment]
It looks like you can't have "slaves" the way the example you sent works. Redeeming gift code requires the id of the channel it's sent on. And redeeming gift code from the slave channel where the master doesn't have right make the requests return access right error.
I can make the slaves sent the gift link to Master through a webhook so he has the right to claim it but I don't know if it will be fast enough.

**Comment by Jev1337** [comment]
I want this too! It basically looks for gifts, once it finds one, it redeems it but on the main account instead!

**Comment by hellbound1337** [comment]
this is possible without the channel id. have a look at the sniper in my repos

**Comment by Jev1337** [comment]
It is possible without channel ID!

**Comment by Patrick187** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/35432352/94355834-45b96280-0090-11eb-9756-2ecb0f03696d.png)
What is the problem?

**Comment by Vedzaa** [comment]
pls don't post about issue not related to the original post, search in closed one if anyone have talked about it in the past or open a new issue next time. Never mind, here is one issue talking about this error #6, basically this error happens to some people because of the fact you're doing a self bot but the bot will work without any problem with this error and I can't do anything about as it comes from a dependency I use.

>

> It is possible without channel ID!

I don't have time to do add this feature now but thanks for the info ! I just found that you can claim nitro from gift inventory, so I should use this request instead
